@environment = dev
@baseUrl = http://localhost:3000
@user_email = owner1@example.com
@user_password = test123

### LOGIN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{ user_email}}",
  "password": "{{ user_password }}"
}

### REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "owner2@example.com",
  "password": "test123",
  "roleName": "owner"
}

### Get me
@token = {{login.response.body.token}}

### Get Profile details
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}

### UPDATE Profile
POST {{baseUrl}}/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "firstName": "Lisa",
  "lastName": "Larsson",
  "bio": "Looking for work!",
  "location": "Stockholm",
  "dogBreed": "Golden Retriever",
  "servicesOffered": "Weekend sitting, basic training, grooming"
}